### ISSUE TITLE
[vdsql] Polishing vdsql, list of issues

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#2203]
- [ ] #282: Select starting table in postgres from command-line
- [ ] #579: [Postgres] Allow inserting / deleting rows
- [ ] #522: [postgres] parms in options
- [ ] #586: SQL query data
- [ ] #727: [postgres] Transaction error when viewing table
- [ ] #729: Integrate generic SQL loader
