### ISSUE TITLE
[roadmap] .pkg MacOS installer

### ISSUE THREAD

**Issue by saulpw** [saulpw/visidata#253]
VisiData needs a .dmg that non-terminal-savvy users can download.

- [x] include Python 3.7 and pip for users who don't have python installed
- [x] include reasonable set of dependencies for common loaders
- [x] install with single click
- [ ] application icon on desktop, a small wrapper to pick one or more files and launch a terminal with vd in virtualenv

**Comment by saulpw** [comment]
[Build an OSX .pkg installer from Linux using mkbom and xar](https://gist.github.com/SchizoDuckie/2a1a1cc71284e6463b9a])
